careerbrige_django_project1/careerbridge_django_app1/urls.py
from django.urls import path
from . import views
#from careerbridge_django_app1 import views

urlpatterns = [
    #path('',views.home,name='home'),
    path('',views.index,name='index'),
    #path('student_table/', views.students_table,name='student_table')
    path('student_table/',views.student_table,name='student_table')

]

careerbrige_django_project1/careerbrige_django_project1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('careerbridge_django_app1.urls')),
    path('forms/', include('forms_app.urls')),
]

#urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_DIR)
# Serve media files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

careerbrige_django_project1/forms_app/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.form_name_view, name='form_name'),

]

careerbrige_django_project1/careerbridge_django_app1/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField(unique=True)
    course_name = models.CharField(default="Django Training",max_length=50)
    enrollment_date = models.DateField(auto_now_add=True)


def __str__(self):
    return f"{self.first_name} {self.last_name} - {self.course_name}"

careerbrige_django_project1/forms_app/models.py
# forms_app/model.py
from distutils.command.upload import upload

from django.db import models

class Feedback(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    feedback = models.TextField()
    profile_pic = models.ImageField(upload_to='profile_pics/', null=True, blank=True)

    def __str__(self):
        return f"{self.name} - {self.email}"




careerbrige_django_project1/forms_app/forms.py
from django import forms
from django.forms import ClearableFileInput


class FormName(forms.Form):
    name= forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Enter your name'
        })
    )
    email = forms.EmailField(
        widget=forms.EmailInput(attrs={
            'class': 'form-control',
            'placeholder': 'Enter your email'
        })
    )
    feedback = forms.CharField(
        widget=forms.Textarea(attrs={
            'class': 'form-control',
            'placeholder': 'Enter your feedback'
        })
    )
    profile_pic = forms.ImageField(
        required=False,
        widget=forms.ClearableFileInput(attrs={
            'class': 'form-control-file'
        })
    )

careerbrige_django_project1/careerbridge_django_app1/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.http import HttpResponse
from .models import Student

# Create your views here.
#def home(request):
    #return HTTPResponse("welcome to Django Training At CareerBridge....")


def index (request):
    our_dict={'insert_CarrerBridge':"Carrer Bridge Django Training Coming from views.py file of Django App..."}
    return render(request,'careerbridge_django_app1/index.html',context=our_dict)


def student_table(request):
    students = Student.objects.all()
    return render(request, 'careerbridge_django_app1/student_table.html',{'students':students})



careerbrige_django_project1/forms_app/views.py
from django.shortcuts import render
from .forms import FormName
from .models import Feedback

# Create your views here.
def form_name_view(request):
    form= FormName()
    profile_pic_url = None  #Initialize profile picture URL

    if request.method == 'POST':
        form= FormName(request.POST, request.FILES)  # Handle file uploads
        #form = FormName(request.POST)
        if form.is_valid():
            #Extra cleaned data from the form
            name=form.cleaned_data['name']
            email=form.cleaned_data['email']
            feedback=form.cleaned_data['feedback']
            profile_pic = form.cleaned_data.get('profile_pic')


            #Save data to the database
            feedback_instance = Feedback.objects.create(
                name=name,
                email=email,
                feedback=feedback,
                profile_pic=profile_pic
            )
            # Get the URL of the uploaded profile picture
            if profile_pic:
                profile_pic_url = feedback_instance.profile_pic.url

            # Print formatted output in the terminal
            print("\n" + "=" * 50)
            print("User Form Submission".center(30))
            print("=" * 50)
            print(f"Name: {name}")
            print(f"Email: {email}")
            print(f"Feedback: {feedback}")
            #print("=" * 50 + "\n")




            #for field, value in form.cleaned_data.items():
                #print(f"{field.capitalize()}: {value}")
            if profile_pic:
                print(f"Profile Picture: {profile_pic_url}")
                print("=" * 50 + "\n")

    return render(request, 'forms_app/form_page.html', {
        'form': form,
        'profile_pic_url': profile_pic_url
    })



careerbrige_django_project1/templates/careerbridge_django_app1/index.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <link rel="stylesheet"  type=" text/css" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/script.js' %}"></script>

    <title>CarrerBridgeDjangoApp</title>
  </head>
  <body>
    <h1>Carrer Bridge Django training Program</h1>
    <br>
    <hr>
    {{insert_CarrerBridge}}
    <br>
    <hr>
    <img src="{% static 'Images/logo.png'%}" alt="img not found">
    <br>
    <hr>
    <button type="button" class="btn btn-warning" onclick="displayAnAlert()">Register</button>


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    -->
  </body>
</html>

careerbrige_django_project1/templates/careerbridge_django_app1/student_table.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <title>Student Table Data</title>
     <style>
      body{
      background-color:f8f9fa;
      }
      .container {
        margin-top:50px;
        color:#343a40;
      }
    </style>
  </head>
  <body>
  <div class="container">
    <h1>Registered Student To Django Training at CBT</h1>
    <table class ="table table-bordered table-hover table-striped">
      <thead class="thead-dark">
          <tr>
            <th scope="col">First Name</th>
            <th scope="col">Last Name </th>
            <th scope="col">Email</th>
            <th scope="col">Course</th>
            <th scope="col">Enrollment Date</th>
          </tr>
      </thead>
      <tbody>
        {% for student in students %}
        <tr>
          <td>{{ student.first_name }} </td>
          <td>{{ student.last_name }}</td>
          <td>{{ student.email }}</td>
          <td>{{ student.course_name }}</td>
          <td>{{ student.enrollment_date }}</td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="5" class="text-center">No students registered yet.</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    -->
  </body>
</html>

careerbrige_django_project1/templates/forms_app/form_page.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body class="bg-white">
        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class="col-md-6">
                    <div class="card shadow">
                        <div class="card-header bg-dark text-white">
                            <h4 class="text-center">User Feedback Form</h4>
                        </div>
                        <div class="card-body">
                            <form method="POST" enctype="multipart/form-data" novalidate>
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="id_name">Your Name</label>
                                    {{ form.name }}
                                </div>
                                <div class="form-group">
                                    <label for="id_email">Your Email</label>
                                    {{ form.email }}
                                </div>
                                <div class="form-group">
                                    <label for="id_feedback">Your Feedback</label>
                                    {{ form.feedback }}
                                </div>
                                <div class="form-group">
                                    <label for="id_profile_pic">Upload Profile Picture</label>
                                    {{ form.profile_pic }}
                                </div>
                                <button type="submit" class="btn btn-success btn-block">
                                    submit
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <h1>Hello, world!</h1>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js" integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+" crossorigin="anonymous"></script>
    -->
  </body>
</html>